apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubectl
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kubectl
    spec:
      serviceAccountName: kubectl
      automountServiceAccountToken: true
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest 
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - sleep infinity
      restartPolicy: Always
